### ISSUE TITLE
Feature Tracker

### ISSUE THREAD

**Issue by NexRX** [NexRX/restructed#1]
Anything checked off is merged into the main branch

# Features
- [x] Enum support for views
- [x] Ability to ('base', 'with', 'include', 'using', 'from', 'extend') previous view or model and add or omit on top of it
- [x] Attribute filtering, e.g. a list of attributes to keep (and default to none).
- [ ] Add optional rustdoc arg for the generated model (Used with the first arg(s) being a comment/rustdoc

### Research / Techspikes
Additions that I'm not sure if its possible or easy to add & maintain. Non-commital.
- [ ] Struct level attributes to top of generated model, maybe even at the field level (helpful for defaults on enums etc)

# Support
- [x] Carry over field rust docs
- [x] Paths in the derive list for generated models

# Tweaks & Fixes
- [x] Tweak dependacy feature to not need to be included with them, relying on consumers to import/depend them
- [ ] Docs has so many spelling/grammar mistakes, update that!

**Comment by tgrushka** [comment]
Hey, how come no ability to send attributes? What is this complex `attributes_with` stuff? I've never seen that! Why so hackish?

I tried using this, but cannot use it with `#[serde_with::skip_serializing_none]`, or really any other thing requiring passing specific attributes but not others. Too bad, because PATCH converted to JSON with all None fields set to `null` will delete data (kubernetes patch). Frustrated that none of these patch/partially/optional struct crates (I've tried them all!!!!) allow serializing to JSON skipping None fields. Exhausting!

Roll my own, I guess. The one thing I don't like about Rust: a lot of would-be-useful crates seem to remain perpetually in the "experimental" stage.

**Comment by NexRX** [comment]
Hey @tgrushka If you send me an example of what your trying to do, I can make it easier for you if its not already easy enough (probably isn't 😊). I would of thought all you needed was `attributes_with = "all"`. The reason its somewhat complex is that depending on what your trying to do this stuff breaks easily, hence the configuration
